### ISSUE TITLE
Update S2699: to support NFluent

### ISSUE THREAD

**Issue by agigleux** [SonarSource/sonar-dotnet#1353]
Once implemented, https://jira.sonarsource.com/browse/RSPEC-3413 should be amended to list NFluent, Shoudly and FluentAssertions 5.x

- [x]  NFluent (http://www.n-fluent.net/) Done in #4862
- [x] Shouldly (https://github.com/shouldly/shouldly) Support was already there, tested in #4863
- [x] FluentAssertions 5.x => Done in #2715
- [x] [NSubstitute](https://nsubstitute.github.io/) (from [community](https://community.sonarsource.com/t/how-to-make-sonarqube-recognize-nsubstitute-assertions/13432)) => Done in  #2709

**Comment by costin-zaharia-sonarsource** [comment]
Added support for NSubstitute (4.2.1) in #2709

**Comment by costin-zaharia-sonarsource** [comment]
Updated the codebase to support FluentAssertions 5 in #2715

**Comment by andrei-epure-sonarsource** [comment]
Shouldly is already supported implicitly (we consider any method containing "Should" to be an assertion).

**Comment by agigleux** [comment]
Can you update the description of the rule to make it clear which UT Framework is supported?

https://rules.sonarsource.com/csharp/RSPEC-2699 is not listing NFluent, Shoudly for example.

**Comment by csaba-sagi-sonarsource** [comment]
> @csaba-sagi-sonarsource Can you update the description of the rule to make it clear which UT Framework is supported?
> 
> https://rules.sonarsource.com/csharp/RSPEC-2699 is not listing NFluent, Shoudly for example.

Thank you @agigleux for pointing it out.
The description got updated in #4867, so I am closing the issue once more :)
