### ISSUE TITLE
Improve S3247: Rule should recommend pattern matching for new C# instead of as

### ISSUE THREAD

**Issue by Evangelink** [SonarSource/sonar-dotnet#2120]
### Description

Currently, when the rule detects a `is` check in an `if` followed by a cast, it raises an issue recommending to `Replace this type-check-and-cast sequence with an 'as' and a null check.`. While this is still relevant it makes more sense for modern applications to suggest to use pattern matching instead.

### Repro steps

https://sonarcloud.io/project/issues?id=sonarlint-visualstudio&issues=AWMB0jMemtQEh111EJCu&open=AWMB0jMemtQEh111EJCu

### TODO

- [ ] Rule should be updated
- [ ] RSPEC should be updated
- [ ] Tests should be updated

When implementing this rule consider also https://github.com/SonarSource/sonar-dotnet/issues/223
