### ISSUE TITLE
Rule S2077: support for additional database libraries

### ISSUE THREAD

**Issue by csaba-sagi-sonarsource** [SonarSource/sonar-dotnet#3905]
S2077 should follow rule S3649 (all the sinks defined in S3649 should be supported in S2077)
Like: PetaPoco, OrmLite, Dapper, NHibernate, etc.

Related discussions:
- https://github.com/SonarSource/sonar-dotnet/issues/2800#issuecomment-584036701
- https://jira.sonarsource.com/browse/RSPEC-4873?focusedCommentId=232648&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-232648

- [x] Dapper #6177
- [x] EntityFramework (not core, but fw) #6188
- [x] EntityFramework core - see: #4533 https://github.com/SonarSource/sonar-dotnet/pull/6186
- [x] Owin (Is this [Katana](https://github.com/aspnet/AspNetKatana)? If so, I can not find anything database related in the docs.)
- [x] Microsoft.SqlServer.Compact (aka SQL CE, already supported)
- [x] NHibernate #6193
- [x] PetaPoco #6192
- [x] OrmLite #6194
- [x] System.Data.Odbc (Already supported)
- [x] System.Data.SqlClient (Already supported), but the newer [Microsoft.Data.Sqlclient](https://learn.microsoft.com/en-us/dotnet/api/microsoft.data.sqlclient) is missing (Created  #6205 and informed AppSec)
- [x] MySql (Already supported), but there are alternative providers to the Oracle one out there: https://mysqlconnector.net/

**Comment by costin-zaharia-sonarsource** [comment]
[S3649 sinks](https://github.com/SonarSource/sonar-security/blob/master/sonar-security-plugin/src/main/resources/com/sonar/security/config/roslyn.sonaranalyzer.security.cs/sinks/S3649.json)
