### ISSUE TITLE
S138, S1541, S3776 - exclude static local functions from computing method complexity

### ISSUE THREAD

**Issue by andrei-epure-sonarsource** [SonarSource/sonar-dotnet#5625]
To reduce noise, static local functions should be excluded from computing the cognitive complexity of methods. As long as they are static, they should be considered a separate piece of code.

I expect this should not be difficult so it would be good to exclude static local functions from all function complexity rules: 

- [x] Sonar Way - S3776 - fixed by #5668
- [x] non Sonar Way - S138 - fixed by #5669
- [x] non Sonar Way - S1541 - fixed by #5678 

A second step should ensure that S3776 runs on static local functions separately (different follow-up ticket).
