### ISSUE TITLE
S138, S1541, S3776 - compute complexity for static local functions as a separate piece of code.

### ISSUE THREAD

**Issue by mary-georgiou-sonarsource** [SonarSource/sonar-dotnet#5680]
Follow-up issue for #5625.

Static local functions have been excluded from complexity computation for rules S3776, S138, and S1541.
However, they should be treated as separate methods themselves.

- [ ] Sonar Way - S3776  - Compute complexity for static local functions in top-level statements or the static local functions which are nested in methods. #5697 
- [ ] non Sonar Way - S138  - Compute complexity for the static local functions which are nested in methods. #5690 
- [ ] non Sonar Way - S1541 - Compute complexity for static local functions in top-level statements or the static local functions which are nested in methods. #5695
