### ISSUE TITLE
 Improve S2259: Support C# 9 and C# 10 syntax

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#5973]
Improve implementation of S2259 on the new SE to fully migrate the rule to the new engine.

Required scaffolding was done in #5862

Support:
* [x] `ValidatedNotNull` attribute #6036
* [x] Common: string.IsNullOrEmpty (generate Null and NotNull) #6054
* [x] C# 8: set NotNull to string literals `""`, should fix C# 8 NullCoalescenceAssignment_NotNull #6051
* [x] Common: NullConst field
* [x] Common: (new NullPointerDereferenceWithFields())._foo1.ToString(); FP
* [x] Common: `CallToMethodsShouldResetFieldConstraints` Invoking methods or extensions on `this` should forget nonstatic `fields` state #6060 and #6065
* [x] Common: `AsyncAwait` awaiting task should forget outer scope fields and locals?
* [x] Common: Investiagte `Repro_4784.IssueReported`
* [x] C# 7: Null_Conditional_Is_Null
* [x] Remove `// FIXME Non-compliant FP` annotations, close repro issues

**Comment by pavel-mikula-sonarsource** [comment]
`ValidatedNotNullAttribute`, consider new C# 8 nullability annotations

**Comment by pavel-mikula-sonarsource** [comment]
Support `throw` - notify check that there's branching going on

**Comment by pavel-mikula-sonarsource** [comment]
Implement `NullPointerDereference.ShouldExecute`

**Comment by mm6502** [comment]
Support [`File Scoped Namespaces`](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-10.0/file-scoped-namespaces)

**Comment by pavel-mikula-sonarsource** [comment]
@mm6502 how are File Scoped Namespaces related to S2259?

**Comment by mm6502** [comment]
They are not. I searched for "support C# 10 syntax". This was the only issue with matching title, and I did not know what "Improve S2259" means. Seemed like good fit.

**Comment by pavel-mikula-sonarsource** [comment]
@mm6502 We've addressed some File Scoped Namespaces issues in the last release.
https://github.com/SonarSource/sonar-dotnet/releases/tag/8.44.0.52574

If you have this version and are facing some False Positive / False Negative, please create a new issue in this repository with reproducer and rule ID
