### ISSUE TITLE
S2259: Take nullable flow state from Roslyn into account

### ISSUE THREAD

**Issue by martin-strecker-sonarsource** [SonarSource/sonar-dotnet#6092]
`semanticModel.GetTypeInfo(someNode).Nullability` exposes information about the nullable flow-state as seen by the Roslyn compiler, if `#nullable enable` was active in the compilation. See the [Nullability Public API Design Notes.md](https://github.com/dotnet/roslyn/blob/main/docs/compilers/CSharp/Nullability%20Public%20API%20Design%20Notes.md) for details about `NullableFlowState`.
Before we report any S2259 we should make sure, that `NullableFlowState` of the node in question is not `NotNull`. The Roslyn compiler was smarter than we and figured out, that the expression is supposed to be not null.
Adding this, would fix #6082 and many other issues that e.g. rely on the [nullable attributes](https://docs.microsoft.com/dotnet/csharp/language-reference/attributes/nullable-analysis).

* [x] Create a lightup shim for `TypeInfo` to expose the [`Nullability`](https://docs.microsoft.com/dotnet/api/microsoft.codeanalysis.typeinfo.nullability?view=roslyn-dotnet-4.2.0) property #6099
* [x] Expose `nodeContext.SemanticModel` in SymbolicRuleCheck to allow checks to query for the flow info #6116
* [x] Use the flow state information to suppress any FPs in NullPointerDereferenceBase.cs #6116
* [ ] Use the flow state information in the engine itself to increase precision in certain cases.
* [ ] Optional: Add lightup shim for [SemanticModel.GetNullableContext](https://docs.microsoft.com/dotnet/api/microsoft.codeanalysis.semanticmodel.getnullablecontext)

`SemanticModel.GetNullableContext` can be used to determine, if the `TypeInfo` query is useful or not. I think `NullableContextOptions.Warnings` flag must be set to get any useful result. See also [CSharpCompilationOptions.NullableContextOptions](
https://docs.microsoft.com/en-us/dotnet/api/microsoft.codeanalysis.csharp.csharpcompilationoptions.nullablecontextoptions) for another way to access this information on project level (which might be overridden by the `#nullable enable` directive in the compilation unit).

**Comment by martin-strecker-sonarsource** [comment]
The remaining task can have their own issues on demand.
