### ISSUE TITLE
SE: Infer NotNull constraints from structs and literals

### ISSUE THREAD

**Issue by pavel-mikula-sonarsource** [SonarSource/sonar-dotnet#6105]
We need to build NotNull for structs and literals too. Same as the old engine.

This will change some existing code around pattern matching and other places that has `IsStruct` or `IsReferenceType`.
```
object o = 42;
if(o == null) {}
o.ToString(); // Compliant
```

Also
* DefaultExpression (if cannot be null) Fixed in #6864 (see [change](https://github.com/SonarSource/sonar-dotnet/pull/6864/files#diff-958483de1a8a6b3e2ff9596211ccadad0647164c02e091f40864b7f998e2705fR361))
* SafeCast? #6908
* Anonymous object creation https://github.com/SonarSource/sonar-dotnet/issues/6105#issuecomment-1458012493
* Literals (character, numeric) Fixed in #6864 (see [change](https://github.com/SonarSource/sonar-dotnet/pull/6864/files#diff-958483de1a8a6b3e2ff9596211ccadad0647164c02e091f40864b7f998e2705fR436))
* SizeOf #6906
* TypeOf ? For not null arguments https://github.com/SonarSource/sonar-dotnet/issues/6105#issuecomment-1458011373
* Range #6867
* Index #6867

Also:

* [x] Consider adding "NotNull" constraint to "SymbolicValue.True" directly (do we have operations, that can be null and true/false at the same time? probably not) #6903
* [x] Avoid allocations in ProgramState.SetOperationConstraint see https://github.com/SonarSource/sonar-dotnet/pull/6864#discussion_r1129202811 #6913
* [x] Shorten num values for ConstraintKind.Object and ConstraintKind.Bool by removing the prefix. [See also](https://sonarsource.slack.com/archives/D03AYCR0XAN/p1678272499306689)
* [x] Make sure WithConstraint(False) for operations also sets "NotNull". https://github.com/SonarSource/sonar-dotnet/pull/6929#discussion_r1140164373 #6995
* [x] Make sure bool constraints learned in is patterns are also having notnull constraint https://github.com/SonarSource/sonar-dotnet/pull/6995/files#r1151722470 Part of  #7019 and follow-ups
* [x] Learn symbol constraints for static fields. https://github.com/SonarSource/sonar-dotnet/pull/6958#issuecomment-1485398724 #6995

**Comment by pavel-mikula-sonarsource** [comment]
Learn NotNull for Constant pattern https://github.com/SonarSource/sonar-dotnet/pull/6059#discussion_r961552977
Learn NotNull on boxing https://github.com/SonarSource/sonar-dotnet/pull/6059#discussion_r961557811

**Comment by martin-strecker-sonarsource** [comment]
### SizeOf

Is already implemented and under test

Implementation:
https://github.com/SonarSource/sonar-dotnet/blob/8dab9119bbdafaa57e40bf98323c2a5575bd201d/analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs#L61

Test:
https://github.com/SonarSource/sonar-dotnet/blob/8dab9119bbdafaa57e40bf98323c2a5575bd201d/analyzers/tests/SonarAnalyzer.UnitTest/SymbolicExecution/Roslyn/RoslynSymbolicExecutionTest.Operations.cs#L804-L809

**Comment by martin-strecker-sonarsource** [comment]
### Anonymous object creation

Already implemented:

https://github.com/SonarSource/sonar-dotnet/blob/8dab9119bbdafaa57e40bf98323c2a5575bd201d/analyzers/src/SonarAnalyzer.Common/SymbolicExecution/Roslyn/OperationDispatcher.cs#L41
