### ISSUE TITLE
Merge rule S4214 onto S4200

### ISSUE THREAD

**Issue by mary-georgiou-sonarsource** [SonarSource/sonar-dotnet#6488]
Why?

S4214 and S4200 are having the following problems:
- Documentation is unclear (bad wording like “virtual machine” or “Platform Invocation Services”)
- They do not support the new [LibraryImportAttribute](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.libraryimportattribute?view=net-7.0)
- There is a big overlap in their functionality

What?
- Deprecate S4214 and remove it from SonarWay
- Mark S4200 as replacement of S4214

How? 

- [x] Deprecate rule S4214 (replaced by S4200)  (SonarSource/rspec/pull/1445)
- [x] Add support for LibraryImportAttribute (#6603)
- [x] Make sure S4200 finds all issues raised by S4214 (#6530)
- [x] Update the RSpec description/documentation (SonarSource/rspec#1490)
- [x] Register for "Non generated" code only (#6603)

**Comment by martin-strecker-sonarsource** [comment]
Closing, as all sub-tasks are done now.
